const data = {
    products: [
        {
            name: "Nike Slim shirt",
            slug: 'nike-slim-shirt',
            category: 'Shirts',
            image: '/images/p1.jpeg',
            price: 120,
            countInStock: 10,
            brand: 'nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality shirt',
        },
        {
            name: "Adidas Slim shirt",
            slug: 'adidas-slim-shirt',
            category: 'Shirts',
            image: '/images/p2.jpeg',
            price: 250,
            countInStock: 20,
            brand: 'adidas',
            rating: 4.5,
            numReviews: 20,
            description: 'high quality shirt',
        },
        {
            name: "Nike Slim Pant",
            slug: 'nike-slim-pant',
            category: 'Pants',
            image: '/images/p3.jpeg',
            price: 80,
            countInStock: 15,
            brand: 'nike',
            rating: 4.5,
            numReviews: 15,
            description: 'high quality pant',
        },
        {
            name: "Adidas Slim Pant",
            slug: 'adidas-slim-pant',
            category: 'Pants',
            image: '/images/p4.jpeg',
            price: 70,
            countInStock: 12,
            brand: 'adidas',
            rating: 4.8,
            numReviews: 18,
            description: 'high quality pant',
        },
        {
            name: "Bull Slim Pant",
            slug: 'bull-slim-pant',
            category: 'Pants',
            image: '/images/p5.jpeg',
            price: 90,
            countInStock: 12,
            brand: 'adidas',
            rating: 4.8,
            numReviews: 18,
            description: 'high quality pant',
        },
    ],
};

export default data;